/*++

Copyright (c) 

Module Name:

    cybersys.h

Abstract:

    This framework is generated by QuickSYS 0.4

Author:

	<your name>

Environment:

	User or kernel mode.

Revision History:

--*/

#ifndef _CYBERSYS_H
#define _CYBERSYS_H 1

//
// Define the various device type values.  Note that values used by Microsoft
// Corporation are in the range 0-0x7FFF(32767), and 0x8000(32768)-0xFFFF(65535)
// are reserved for use by customers.
//



#endif
